### PR TITLE
fix(types): add missing type for `create()`

### LINKED ISSUE #420: $axios.create() is of type AxiosInstance, not NuxtAxiosInstance.
When we're creating a new axios instance, it returns `AxiosInstance`, not `NuxtAxiosInstance`, hence the errors:

"TS2740: Type 'AxiosInstance' is missing the following properties from type 'NuxtAxiosInstance': $request, $get, $delete, $head, and 18 more."

https://github.com/nuxt/typescript/issues/447#issuecomment-698191456

### PR DESCRIPTION
**Pull request by farnabaz**
Add missing type for `create()` function inside `NuxtAxiosInstance`

resolves #420

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -22,6 +22,8 @@ interface NuxtAxiosInstance extends AxiosStatic {
   onError(callback: (error: AxiosError) => void): void
   onRequestError(callback: (error: AxiosError) => void): void
   onResponseError(callback: (error: AxiosError) => void): void
+
+  create(options: AxiosRequestConfig): NuxtAxiosInstance
```
Comment (pi0) [inline types/index.d.ts:26]:
```suggestion
  create(options?: AxiosRequestConfig): NuxtAxiosInstance
```
