### PR TITLE
fix: preserve default headers with custom headers

### LINKED ISSUE #411: Broken server side request with cookies in 5.12.2
After upgrading from 5.12.1 to 5.12.2 a server side axios request seems like does not send the original request cookies. `proxyHeaders` is tuned on and it seems to work so I think it is a breaking change in axios itself. 5.12.1 used axios 0.19.2 but  5.12.2 uses axios 0.20.0  and it has a lot of changes https://github.com/axios/axios/compare/v0.19.2...v0.20.0

### PR DESCRIPTION
**Pull request by pi0**
There is a breaking change with axios [axios/axios@v0.19.2...v0.20.0](https://github.com/axios/axios/compare/v0.19.2...v0.20.0) that when passing headers config when calling `axios`, it discards `defaults.headers.common` (used for both config and `setHeader` utility.

resolves #411 

**Update:** Axios regression found by @1ed regarding defaults overriding: https://github.com/axios/axios/pull/2844 <3

---

Test flow for #411:

- `/api/cookie` endpoint that simply returns value of `mycookie` header if set
- Make a random string in client-side and set cookie "`mycookie`"
- Make SSR request
  - SSR request makes a call to `/api/cookie` in `asyncData` using `$axios` to check what headers are passed to API when using axios in server side
- Value is checked against initial random one (and passing)

### Locally trying:

 - Clone repo and run `yarn install`
 - Switch to `fix/411` branch
 - Run `yarn dev`
 - Go to http://localhost:3000/cookie

### CODE REVIEW

File: test/fixture/pages/cookie.vue [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+  <div>
+    <pre style="display: none">_req:{{ reqCookie }}</pre>
+    <p>Pass: {{ pass }}</p>
+  </div>
+</template>
+
+<script>
+export default {
+  async asyncData ({ app }) {
+    const reqCookie = (await app.$axios.$get('/cookie')) + ''
```
Comment (1ed) [inline test/fixture/pages/cookie.vue:11]:
```suggestion
    const reqCookie = (await app.$axios.$get('/cookie', {
      headers: { Accept: 'application/json' }
    })) + ''
```

Comment (1ed) [reply test/fixture/pages/cookie.vue:11]: If we add a local config it will not be merged with the default config and will not work with the current version, but if you set axios to `0.19.2` it works. I think it was changed in this PR https://github.com/axios/axios/pull/2844
